  import { PrismaClient } from "../src/generated/prisma/index.js";

  const prisma = new PrismaClient();

  async function main() {
    const cars = [
       {
      make: "Acura",
      model: "MDX",
      year: 2022,
      city_mpg: 20,
      highway_mpg: 27,
      cylinders: 6,
      displacement: 3.5,
      drive: "AWD",
      fuel_type: "Gasoline",
      transmission: "Automatic",
      class: "SUV",
      combination_mpg: 23,
      imageUrls: ["/pictures/acura_mdx_2022/p0.jpg", "/pictures/acura_mdx_2022/p1.jpg", "/pictures/acura_mdx_2022/p2.jpg",
        "/pictures/acura_mdx_2022/p3.jpg"
      ]
    },
    {
      make: "Alfa Romeo",
      model: "Giulia",
      year: 2021,
      city_mpg: 24,
      highway_mpg: 33,
      cylinders: 4,
      displacement: 2.0,
      drive: "RWD",
      fuel_type: "Gasoline",
      transmission: "Automatic",
      class: "Sedan",
      combination_mpg: 27,
      imageUrls: ["/pictures/alpha_romeo_guilia_2021/p0.jpg", "/pictures/alpha_romeo_guilia_2021/p1.jpg", "/pictures/alpha_romeo_guilia_2021/p2.jpg",
        "/pictures/alpha_romeo_guilia_2021/p3.jpg"]
    },
    {
      make: "Aston Martin",
      model: "Vantage",
      year: 2021,
      city_mpg: 15,
      highway_mpg: 22,
      cylinders: 8,
      displacement: 4.0,
      drive: "RWD",
      fuel_type: "Gasoline",
      transmission: "Automatic",
      class: "Coupe",
      combination_mpg: 18,
      imageUrls: ["/pictures/aston_martin_vantage_2021/p0.jpg", "/pictures/aston_martin_vantage_2021/p1.jpg", "/pictures/aston_martin_vantage_2021/p2.jpg",
        "/pictures/aston_martin_vantage_2021/p3.jpg"]
    },
    {
      make: "Audi",
      model: "A4",
      year: 2022,
      city_mpg: 24,
      highway_mpg: 31,
      cylinders: 4,
      displacement: 2.0,
      drive: "AWD",
      fuel_type: "Gasoline",
      transmission: "Automatic",
      class: "Sedan",
      combination_mpg: 27,
      imageUrls: ["/pictures/audi_a4_2022/p0.jpg", "/pictures/audi_a4_2022/p1.jpg", "/pictures/audi_a4_2022/p2.jpg",
        "/pictures/audi_a4_2022/p3.jpg"]
    },
    {
      make: "Bentley",
      model: "Continental GT",
      year: 2021,
      city_mpg: 12,
      highway_mpg: 20,
      cylinders: 12,
      displacement: 6.0,
      drive: "AWD",
      fuel_type: "Gasoline",
      transmission: "Automatic",
      class: "Coupe",
      combination_mpg: 15,
      imageUrls: ["/pictures/bently_continental_gt_2021/p0.jpg", "/pictures/bently_continental_gt_2021/p1.jpg", "/pictures/bently_continental_gt_2021/p2.jpg",
        "/pictures/bently_continental_gt_2021/p3.jpg"]
    },
    {
      make: "BMW",
      model: "X5",
      year: 2022,
      city_mpg: 21,
      highway_mpg: 26,
      cylinders: 6,
      displacement: 3.0,
      drive: "AWD",
      fuel_type: "Gasoline",
      transmission: "Automatic",
      class: "SUV",
      combination_mpg: 23,
      imageUrls: ["/pictures/bmw_x5_2022/p0.png", "/pictures/bmw_x5_2022/p1.png", "/pictures/bmw_x5_2022/p2.png",
        "/pictures/bmw_x5_2022/p3.png"]
    },
    {
      make: "Buick",
      model: "Enclave",
      year: 2021,
      city_mpg: 18,
      highway_mpg: 26,
      cylinders: 6,
      displacement: 3.6,
      drive: "FWD",
      fuel_type: "Gasoline",
      transmission: "Automatic",
      class: "SUV",
      combination_mpg: 21,
      imageUrls: ["/pictures/buick_enclave_2021/p0.jpg", "/pictures/buick_enclave_2021/p1.jpg", "/pictures/buick_enclave_2021/p2.jpg",
        "/pictures/buick_enclave_2021/p3.jpg"]
    },
    {
      make: "Cadillac",
      model: "Escalade",
      year: 2022,
      city_mpg: 14,
      highway_mpg: 23,
      cylinders: 8,
      displacement: 6.2,
      drive: "AWD",
      fuel_type: "Gasoline",
      transmission: "Automatic",
      class: "SUV",
      combination_mpg: 17,
      imageUrls: ["/pictures/cadillac_escalade_2022/p0.jpg", "/pictures/cadillac_escalade_2022/p1.jpg", "/pictures/cadillac_escalade_2022/p2.jpg",
        "/pictures/cadillac_escalade_2022/p3.jpg"]
    },
    {
      make: "Chevrolet",
      model: "Tahoe",
      year: 2021,
      city_mpg: 15,
      highway_mpg: 22,
      cylinders: 8,
      displacement: 5.3,
      drive: "RWD",
      fuel_type: "Gasoline",
      transmission: "Automatic",
      class: "SUV",
      combination_mpg: 18,
      imageUrls: ["/pictures/chevrolet_tahoe_2021/p0.jpg", "/pictures/chevrolet_tahoe_2021/p1.jpg", "/pictures/chevrolet_tahoe_2021/p2.jpg",
        "/pictures/chevrolet_tahoe_2021/p3.jpg"]
    },
    {
      make: "Chrysler",
      model: "Pacifica",
      year: 2022,
      city_mpg: 19,
      highway_mpg: 28,
      cylinders: 6,
      displacement: 3.6,
      drive: "FWD",
      fuel_type: "Gasoline",
      transmission: "Automatic",
      class: "Minivan",
      combination_mpg: 22,
      imageUrls: ["/pictures/chryslar_pacifica_2022/p0.jpg", "/pictures/chryslar_pacifica_2022/p1.jpg", "/pictures/chryslar_pacifica_2022/p2.jpg",
        "/pictures/chryslar_pacifica_2022/p3.jpg"]
    },
    {
      make: "Citroen",
      model: "C3",
      year: 2021,
      city_mpg: 27,
      highway_mpg: 35,
      cylinders: 3,
      displacement: 1.2,
      drive: "FWD",
      fuel_type: "Gasoline",
      transmission: "Manual",
      class: "Hatchback",
      combination_mpg: 30,
      imageUrls: ["/pictures/citroe_c3_2021/p0.jpg", "/pictures/citroe_c3_2021/p1.jpg", "/pictures/citroe_c3_2021/p2.jpg",
        "/pictures/citroe_c3_2021/p3.jpg"]
    },
    {
      make: "Dodge",
      model: "Charger",
      year: 2021,
      city_mpg: 19,
      highway_mpg: 30,
      cylinders: 6,
      displacement: 3.6,
      drive: "RWD",
      fuel_type: "Gasoline",
      transmission: "Automatic",
      class: "Sedan",
      combination_mpg: 23,
      imageUrls: ["/pictures/dodge_charger_2021/p0.jpg", "/pictures/dodge_charger_2021/p1.jpg", "/pictures/dodge_charger_2021/p2.jpg",
        "/pictures/dodge_charger_2021/p3.jpg"]
    },
    {
      make: "Ferrari",
      model: "Roma",
      year: 2022,
      city_mpg: 15,
      highway_mpg: 22,
      cylinders: 8,
      displacement: 3.9,
      drive: "RWD",
      fuel_type: "Gasoline",
      transmission: "Automatic",
      class: "Coupe",
      combination_mpg: 18,
      imageUrls: ["/pictures/ferrari_roma_2022/p0.jpg", "/pictures/ferrari_roma_2022/p1.jpg", "/pictures/ferrari_roma_2022/p2.jpg",
        "/pictures/ferrari_roma_2022/p3.jpg"]
    },
    // {
    //   make: "Fiat",
    //   model: "500",
    //   year: 2021,
    //   city_mpg: 28,
    //   highway_mpg: 33,
    //   cylinders: 4,
    //   displacement: 1.4,
    //   drive: "FWD",
    //   fuel_type: "Gasoline",
    //   transmission: "Manual",
    //   class: "Hatchback",
    //   combination_mpg: 30,
    //   imageUrls: ["https://www.fiat.com/500"]
    // },
    // {
    //   make: "Ford",
    //   model: "Mustang",
    //   year: 2022,
    //   city_mpg: 21,
    //   highway_mpg: 32,
    //   cylinders: 4,
    //   displacement: 2.3,
    //   drive: "RWD",
    //   fuel_type: "Gasoline",
    //   transmission: "Manual",
    //   class: "Coupe",
    //   combination_mpg: 25,
    //   imageUrls: ["https://www.edmunds.com/ford/mustang/2022/pictures/"]
    // },
    // {
    //   make: "GMC",
    //   model: "Sierra",
    //   year: 2021,
    //   city_mpg: 16,
    //   highway_mpg: 22,
    //   cylinders: 8,
    //   displacement: 5.3,
    //   drive: "4WD",
    //   fuel_type: "Gasoline",
    //   transmission: "Automatic",
    //   class: "Truck",
    //   combination_mpg: 19,
    //   imageUrls: ["https://www.edmunds.com/gmc/sierra-1500/2021/pictures/"]
    // },
    // {
    //   make: "Honda",
    //   model: "Civic",
    //   year: 2022,
    //   city_mpg: 30,
    //   highway_mpg: 38,
    //   cylinders: 4,
    //   displacement: 2.0,
    //   drive: "FWD",
    //   fuel_type: "Gasoline",
    //   transmission: "Automatic",
    //   class: "Sedan",
    //   combination_mpg: 33,
    //   imageUrls: ["https://www.edmunds.com/honda/civic/2022/pictures/"]
    // },
    // {
    //   make: "Hyundai",
    //   model: "Sonata",
    //   year: 2022,
    //   city_mpg: 27,
    //   highway_mpg: 37,
    //   cylinders: 4,
    //   displacement: 2.5,
    //   drive: "FWD",
    //   fuel_type: "Gasoline",
    //   transmission: "Automatic",
    //   class: "Sedan",
    //   combination_mpg: 31,
    //   imageUrls: ["https://www.edmunds.com/hyundai/sonata/2022/pictures/"]
    // },
    // {
    //   make: "Infiniti",
    //   model: "Q50",
    //   year: 2021,
    //   city_mpg: 23,
    //   highway_mpg: 31,
    //   cylinders: 4,
    //   displacement: 2.0,
    //   drive: "RWD",
    //   fuel_type: "Gasoline",
    //   transmission: "Automatic",
    //   class: "Sedan",
    //   combination_mpg: 26,
    //   imageUrls: ["https://www.edmunds.com/infiniti/q50/2021/pictures/"]
    // },
    // {
    //   make: "Jaguar",
    //   model: "XF",
    //   year: 2021,
    //   city_mpg: 23,
    //   highway_mpg: 31,
    //   cylinders: 4,
    //   displacement: 2.0,
    //   drive: "RWD",
    //   fuel_type: "Gasoline",
    //   transmission: "Automatic",
    //   class: "Sedan",
    //   combination_mpg: 27,
    //   imageUrls: ["https://www.edmunds.com/jaguar/xf/2021/pictures/"]
    // },
    // {
    //   make: "Jeep",
    //   model: "Wrangler",
    //   year: 2022,
    //   city_mpg: 17,
    //   highway_mpg: 23,
    //   cylinders: 4,
    //   displacement: 2.0,
    //   drive: "4WD",
    //   fuel_type: "Gasoline",
    //   transmission: "Manual",
    //   class: "SUV",
    //   combination_mpg: 20,
    //   imageUrls: ["https://www.edmunds.com/jeep/wrangler/2022/pictures/"]
    // },
    // {
    //   make: "Kia",
    //   model: "Sorento",
    //   year: 2022,
    //   city_mpg: 22,
    //   highway_mpg: 29,
    //   cylinders: 4,
    //   displacement: 2.5,
    //   drive: "AWD",
    //   fuel_type: "Gasoline",
    //   transmission: "Automatic",
    //   class: "SUV",
    //   combination_mpg: 25,
    //   imageUrls: ["https://www.edmunds.com/kia/sorento/2022/pictures/"]
    // },
    // {
    //   make: "Lamborghini",
    //   model: "Huracan",
    //   year: 2021,
    //   city_mpg: 13,
    //   highway_mpg: 18,
    //   cylinders: 10,
    //   displacement: 5.2,
    //   drive: "AWD",
    //   fuel_type: "Gasoline",
    //   transmission: "Automatic",
    //   class: "Coupe",
    //   combination_mpg: 15,
    //   imageUrls: ["https://www.lamborghini.com/en-en/models/huracan"]
    // },
    // {
    //   make: "Land Rover",
    //   model: "Range Rover",
    //   year: 2022,
    //   city_mpg: 17,
    //   highway_mpg: 23,
    //   cylinders: 6,
    //   displacement: 3.0,
    //   drive: "AWD",
    //   fuel_type: "Gasoline",
    //   transmission: "Automatic",
    //   class: "SUV",
    //   combination_mpg: 20,
    //   imageUrls: ["https://www.edmunds.com/land-rover/range-rover/2022/pictures/"]
    // },
    // {
    //   make: "Lexus",
    //   model: "RX",
    //   year: 2022,
    //   city_mpg: 20,
    //   highway_mpg: 27,
    //   cylinders: 6,
    //   displacement: 3.5,
    //   drive: "AWD",
    //   fuel_type: "Gasoline",
    //   transmission: "Automatic",
    //   class: "SUV",
    //   combination_mpg: 23,
    //   imageUrls: ["https://www.edmunds.com/lexus/rx/2022/pictures/"]
    // },
    // {
    //   make: "Lincoln",
    //   model: "Navigator",
    //   year: 2021,
    //   city_mpg: 16,
    //   highway_mpg: 22,
    //   cylinders: 8,
    //   displacement: 5.0,
    //   drive: "AWD",
    //   fuel_type: "Gasoline",
    //   transmission: "Automatic",
    //   class: "SUV",
    //   combination_mpg: 19,
    //   imageUrls: ["https://www.edmunds.com/lincoln/navigator/2021/pictures/"]
    // },
    // {
    //   make: "Maserati",
    //   model: "Ghibli",
    //   year: 2021,
    //   city_mpg: 17,
    //   highway_mpg: 24,
    //   cylinders: 6,
    //   displacement: 3.0,
    //   drive: "RWD",
    //   fuel_type: "Gasoline",
    //   transmission: "Automatic",
    //   class: "Sedan",
    //   combination_mpg: 20,
    //   imageUrls: ["https://www.maserati.com/maserati/international/en/models/ghibli"]
    // },
    // {
    //   make: "Mazda",
    //   model: "CX-5",
    //   year: 2022,
    //   city_mpg: 24,
    //   highway_mpg: 30,
    //   cylinders: 4,
    //   displacement: 2.5,
    //   drive: "AWD",
    //   fuel_type: "Gasoline",
    //   transmission: "Automatic",
    //   class: "SUV",
    //   combination_mpg: 27,
    //   imageUrls: ["https://www.edmunds.com/mazda/cx-5/2022/pictures/"]
    // },
    // {
    //   make: "McLaren",
    //   model: "720S",
    //   year: 2021,
    //   city_mpg: 15,
    //   highway_mpg: 22,
    //   cylinders: 8,
    //   displacement: 4.0,
    //   drive: "RWD",
    //   fuel_type: "Gasoline",
    //   transmission: "Automatic",
    //   class: "Coupe",
    //   combination_mpg: 18,
    //   imageUrls: ["https://cars.mclaren.com/en/720s"]
    // },
    // {
    //   make: "Mercedes-Benz",
    //   model: "E-Class",
    //   year: 2022,
    //   city_mpg: 21,
    //   highway_mpg: 30,
    //   cylinders: 4,
    //   displacement: 2.0,
    //   drive: "RWD",
    //   fuel_type: "Gasoline",
    //   transmission: "Automatic",
    //   class: "Sedan",
    //   combination_mpg: 25,
    //   imageUrls: ["https://www.edmunds.com/mercedes-benz/e-class/2022/pictures/"]
    // },
    // {
    //   make: "MINI",
    //   model: "Cooper",
    //   year: 2023,
    //   city_mpg: 32,
    //   highway_mpg: 38,
    //   cylinders: 3,
    //   displacement: 1.5,
    //   drive: "FWD",
    //   fuel_type: "Gasoline",
    //   transmission: "Manual",
    //   class: "Hatchback",
    //   combination_mpg: 35,
    //   imageUrls: ["https://www.edmunds.com/mini/cooper/2023/pictures/"]
    // },
    // {
    //   make: "Mitsubishi",
    //   model: "Outlander",
    //   year: 2022,
    //   city_mpg: 24,
    //   highway_mpg: 31,
    //   cylinders: 4,
    //   displacement: 2.5,
    //   drive: "AWD",
    //   fuel_type: "Gasoline",
    //   transmission: "Automatic",
    //   class: "SUV",
    //   combination_mpg: 27,
    //   imageUrls: ["https://www.edmunds.com/mitsubishi/outlander/2022/pictures/"]
    // },
    // {
    //   make: "Nissan",
    //   model: "Altima",
    //   year: 2022,
    //   city_mpg: 28,
    //   highway_mpg: 39,
    //   cylinders: 4,
    //   displacement: 2.5,
    //   drive: "FWD",
    //   fuel_type: "Gasoline",
    //   transmission: "Automatic",
    //   class: "Sedan",
    //   combination_mpg: 32,
    //   imageUrls: ["https://www.edmunds.com/nissan/altima/2022/pictures/"]
    // },
    // {
    //   make: "Porsche",
    //   model: "911",
    //   year: 2021,
    //   city_mpg: 18,
    //   highway_mpg: 25,
    //   cylinders: 6,
    //   displacement: 3.0,
    //   drive: "RWD",
    //   fuel_type: "Gasoline",
    //   transmission: "Automatic",
    //   class: "Coupe",
    //   combination_mpg: 21,
    //   imageUrls: ["https://www.edmunds.com/porsche/911/2021/pictures/"]
    // },
    //   {
    //   make: "Ram",
    //   model: "1500",
    //   year: 2021,
    //   city_mpg: 15,
    //   highway_mpg: 22,
    //   cylinders: 6,
    //   displacement: 3.6,
    //   drive: "RWD",
    //   fuel_type: "Gasoline",
    //   transmission: "Automatic",
    //   class: "Truck",
    //   combination_mpg: 18,
    //   imageUrls: [
    //     "https://images.pexels.com/photos/1043476/pexels-photo-1043476.jpeg",
    //     "https://images.pexels.com/photos/1149831/pexels-photo-1149831.jpeg",
    //     "https://images.pexels.com/photos/1708116/pexels-photo-1708116.jpeg",
    //     "https://images.pexels.com/photos/1708120/pexels-photo-1708120.jpeg"
    //   ]
    // },
    // {
    //   make: "Rolls-Royce",
    //   model: "Ghost",
    //   year: 2022,
    //   city_mpg: 12,
    //   highway_mpg: 18,
    //   cylinders: 12,
    //   displacement: 6.6,
    //   drive: "RWD",
    //   fuel_type: "Gasoline",
    //   transmission: "Automatic",
    //   class: "Luxury Sedan",
    //   combination_mpg: 15,
    //   imageUrls: [
    //     "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg",
    //     "https://images.pexels.com/photos/1037995/pexels-photo-1037995.jpeg",
    //     "https://images.pexels.com/photos/358067/pexels-photo-358067.jpeg",
    //     "https://images.pexels.com/photos/358071/pexels-photo-358071.jpeg"
    //   ]
    // },
    // {
    //   make: "Subaru",
    //   model: "Forester",
    //   year: 2022,
    //   city_mpg: 20,
    //   highway_mpg: 27,
    //   cylinders: 4,
    //   displacement: 2.5,
    //   drive: "AWD",
    //   fuel_type: "Gasoline",
    //   transmission: "Automatic",
    //   class: "SUV",
    //   combination_mpg: 23,
    //   imageUrls: [
    //     "https://images.pexels.com/photos/1719649/pexels-photo-1719649.jpeg",
    //     "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg",
    //     "https://images.pexels.com/photos/1708118/pexels-photo-1708118.jpeg",
    //     "https://images.pexels.com/photos/1708123/pexels-photo-1708123.jpeg"
    //   ]
    // },
    // {
    //   make: "Tesla",
    //   model: "Model S",
    //   year: 2023,
    //   city_mpg: 102,
    //   highway_mpg: 105,
    //   cylinders: 0,
    //   displacement: 0,
    //   drive: "AWD",
    //   fuel_type: "Electric",
    //   transmission: "Automatic",
    //   class: "Sedan",
    //   combination_mpg: 103,
    //   imageUrls: [
    //     "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg",
    //     "https://images.pexels.com/photos/1108442/pexels-photo-1108442.jpeg",
    //     "https://images.pexels.com/photos/1149832/pexels-photo-1149832.jpeg",
    //     "https://images.pexels.com/photos/1035715/pexels-photo-1035715.jpeg"
    //   ]
    // },
    // {
    //   make: "Toyota",
    //   model: "RAV4",
    //   year: 2023,
    //   city_mpg: 25,
    //   highway_mpg: 32,
    //   cylinders: 4,
    //   displacement: 2.5,
    //   drive: "AWD",
    //   fuel_type: "Hybrid",
    //   transmission: "Automatic",
    //   class: "SUV",
    //   combination_mpg: 28,
    //   imageUrls: [
    //     "https://images.pexels.com/photos/1708117/pexels-photo-1708117.jpeg",
    //     "https://images.pexels.com/photos/1708119/pexels-photo-1708119.jpeg",
    //     "https://images.pexels.com/photos/1708121/pexels-photo-1708121.jpeg",
    //     "https://images.pexels.com/photos/1708124/pexels-photo-1708124.jpeg"
    //   ]
    // },
    // {
    //   make: "Volkswagen",
    //   model: "Golf",
    //   year: 2023,
    //   city_mpg: 30,
    //   highway_mpg: 36,
    //   cylinders: 4,
    //   displacement: 1.5,
    //   drive: "FWD",
    //   fuel_type: "Gasoline",
    //   transmission: "Manual",
    //   class: "Hatchback",
    //   combination_mpg: 33,
    //   imageUrls: [
    //     "https://images.pexels.com/photos/1708125/pexels-photo-1708125.jpeg",
    //     "https://images.pexels.com/photos/1708126/pexels-photo-1708126.jpeg",
    //     "https://images.pexels.com/photos/1708127/pexels-photo-1708127.jpeg",
    //     "https://images.pexels.com/photos/1708128/pexels-photo-1708128.jpeg"
    //   ]
    // },
    // {
    //   make: "Volvo",
    //   model: "XC90",
    //   year: 2022,
    //   city_mpg: 20,
    //   highway_mpg: 27,
    //   cylinders: 4,
    //   displacement: 2.0,
    //   drive: "AWD",
    //   fuel_type: "Hybrid",
    //   transmission: "Automatic",
    //   class: "SUV",
    //   combination_mpg: 23,
    //   imageUrls: [
    //     "https://images.pexels.com/photos/1708129/pexels-photo-1708129.jpeg",
    //     "https://images.pexels.com/photos/1708130/pexels-photo-1708130.jpeg",
    //     "https://images.pexels.com/photos/1708131/pexels-photo-1708131.jpeg",
    //     "https://images.pexels.com/photos/1708132/pexels-photo-1708132.jpeg"
    //   ]
    // }
    ];

    for (const car of cars) {
      await prisma.car.create({ data: car });
    }
  }

  main()
    .catch((e) => {
      console.error(e);
      process.exit(1);
    })
    .finally(async () => {
      await prisma.$disconnect();
    });

